<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Sponsor;

class SponsorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sponsors = [
            [
                'name' => '156',
                'category' => 'platinum',
                'description' => 'Premium otomobil markası ve distribütör',
                'website' => 'https://156.az',
                'email' => 'info@156.az',
                'phone' => '+994501234567',
                'instagram' => 'https://instagram.com/156',
                'facebook' => 'https://facebook.com/156',
                'linkedin' => 'https://linkedin.com/company/156',
                'partnership_start' => '2023-01-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 1,
            ],
            [
                'name' => 'Bizon',
                'category' => 'gold',
                'description' => 'Güvenilir otomobil servisi ve yedek parça',
                'website' => 'https://bizon.az',
                'email' => 'info@bizon.az',
                'phone' => '+994502345678',
                'instagram' => 'https://instagram.com/bizon',
                'facebook' => 'https://facebook.com/bizon',
                'partnership_start' => '2024-01-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 2,
            ],
            [
                'name' => 'Changan',
                'category' => 'gold',
                'description' => 'Çin otomobil üreticisi',
                'website' => 'https://changan.az',
                'email' => 'info@changan.az',
                'phone' => '+994503456789',
                'instagram' => 'https://instagram.com/changan',
                'partnership_start' => '2024-06-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 3,
            ],
            [
                'name' => 'Maserati',
                'category' => 'platinum',
                'description' => 'Lüks İtalyan otomobil markası',
                'website' => 'https://maserati.az',
                'email' => 'info@maserati.az',
                'phone' => '+994504567890',
                'instagram' => 'https://instagram.com/maserati',
                'facebook' => 'https://facebook.com/maserati',
                'linkedin' => 'https://linkedin.com/company/maserati',
                'partnership_start' => '2023-01-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 4,
            ],
            [
                'name' => 'Seres',
                'category' => 'silver',
                'description' => 'Elektrikli araç üreticisi',
                'website' => 'https://seres.az',
                'email' => 'info@seres.az',
                'phone' => '+994505678901',
                'partnership_start' => '2024-09-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 5,
            ],
            [
                'name' => 'Tegeta Motors',
                'category' => 'silver',
                'description' => 'Otomobil distribütörü',
                'website' => 'https://tegeta.az',
                'email' => 'info@tegeta.az',
                'phone' => '+994506789012',
                'instagram' => 'https://instagram.com/tegeta',
                'partnership_start' => '2024-03-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 6,
            ],
            [
                'name' => 'Volt Avto',
                'category' => 'bronze',
                'description' => 'Elektrikli araç servisi',
                'website' => 'https://voltavto.az',
                'email' => 'info@voltavto.az',
                'phone' => '+994507890123',
                'partnership_start' => '2025-01-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 7,
            ],
            [
                'name' => 'AMSoil',
                'category' => 'bronze',
                'description' => 'Motor yağı ve bakım ürünleri',
                'website' => 'https://amsoil.az',
                'email' => 'info@amsoil.az',
                'phone' => '+994508901234',
                'partnership_start' => '2025-02-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 8,
            ],
            [
                'name' => 'Motul',
                'category' => 'bronze',
                'description' => 'Fransız motor yağı markası',
                'website' => 'https://motul.az',
                'email' => 'info@motul.az',
                'phone' => '+994509012345',
                'instagram' => 'https://instagram.com/motul',
                'partnership_start' => '2025-01-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 9,
            ],
            [
                'name' => 'ZIC Oil',
                'category' => 'bronze',
                'description' => 'Kore motor yağı üreticisi',
                'website' => 'https://zic.az',
                'email' => 'info@zic.az',
                'phone' => '+994501234567',
                'partnership_start' => '2025-03-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 10,
            ],
            [
                'name' => 'Arceo Wheels',
                'category' => 'silver',
                'description' => 'Jant ve lastik distribütörü',
                'website' => 'https://arceo.az',
                'email' => 'info@arceo.az',
                'phone' => '+994502345678',
                'instagram' => 'https://instagram.com/arceo',
                'partnership_start' => '2024-07-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 11,
            ],
            [
                'name' => 'Meysari',
                'category' => 'bronze',
                'description' => 'Otomobil aksesuarları',
                'website' => 'https://meysari.az',
                'email' => 'info@meysari.az',
                'phone' => '+994503456789',
                'partnership_start' => '2025-01-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 12,
            ],
            [
                'name' => 'Bravo Store',
                'category' => 'bronze',
                'description' => 'Otomobil bakım ürünleri',
                'website' => 'https://bravo.az',
                'email' => 'info@bravo.az',
                'phone' => '+994504567890',
                'partnership_start' => '2025-02-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 13,
            ],
            [
                'name' => 'BUZZ TEA',
                'category' => 'bronze',
                'description' => 'İçecek sponsorluğu',
                'website' => 'https://buzztea.az',
                'email' => 'info@buzztea.az',
                'phone' => '+994505678901',
                'instagram' => 'https://instagram.com/buzztea',
                'partnership_start' => '2025-01-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 14,
            ],
            [
                'name' => 'Johnnie Walker',
                'category' => 'gold',
                'description' => 'Premium içecek sponsorluğu',
                'website' => 'https://johnniewalker.az',
                'email' => 'info@johnniewalker.az',
                'phone' => '+994506789012',
                'instagram' => 'https://instagram.com/johnniewalker',
                'facebook' => 'https://facebook.com/johnniewalker',
                'partnership_start' => '2024-01-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 15,
            ],
            [
                'name' => 'Redbull',
                'category' => 'silver',
                'description' => 'Enerji içeceği sponsorluğu',
                'website' => 'https://redbull.az',
                'email' => 'info@redbull.az',
                'phone' => '+994507890123',
                'instagram' => 'https://instagram.com/redbull',
                'facebook' => 'https://facebook.com/redbull',
                'partnership_start' => '2024-06-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 16,
            ],
            [
                'name' => 'Nescafe',
                'category' => 'bronze',
                'description' => 'Kahve sponsorluğu',
                'website' => 'https://nescafe.az',
                'email' => 'info@nescafe.az',
                'phone' => '+994508901234',
                'instagram' => 'https://instagram.com/nescafe',
                'partnership_start' => '2025-01-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 17,
            ],
            [
                'name' => 'RESTAURANTS BY EMİN AĞALAROV',
                'category' => 'gold',
                'description' => 'Premium restoran zinciri',
                'website' => 'https://restaurants.az',
                'email' => 'info@restaurants.az',
                'phone' => '+994509012345',
                'instagram' => 'https://instagram.com/restaurants',
                'facebook' => 'https://facebook.com/restaurants',
                'partnership_start' => '2024-01-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 18,
            ],
            [
                'name' => 'iTicket',
                'category' => 'silver',
                'description' => 'Bilet satış platformu',
                'website' => 'https://iticket.az',
                'email' => 'info@iticket.az',
                'phone' => '+994501234567',
                'instagram' => 'https://instagram.com/iticket',
                'partnership_start' => '2024-08-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 19,
            ],
            [
                'name' => 'KralGames',
                'category' => 'bronze',
                'description' => 'Oyun ve eğlence sponsorluğu',
                'website' => 'https://kralgames.az',
                'email' => 'info@kralgames.az',
                'phone' => '+994502345678',
                'instagram' => 'https://instagram.com/kralgames',
                'partnership_start' => '2025-01-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 20,
            ],
            [
                'name' => 'Misti.az',
                'category' => 'bronze',
                'description' => 'Dijital platform sponsorluğu',
                'website' => 'https://misti.az',
                'email' => 'info@misti.az',
                'phone' => '+994503456789',
                'instagram' => 'https://instagram.com/misti',
                'partnership_start' => '2025-02-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 21,
            ],
            [
                'name' => 'PlusPower',
                'category' => 'bronze',
                'description' => 'Enerji ve güç çözümleri',
                'website' => 'https://pluspower.az',
                'email' => 'info@pluspower.az',
                'phone' => '+994504567890',
                'partnership_start' => '2025-01-01',
                'partnership_end' => '2025-12-31',
                'sort_order' => 22,
            ],
        ];

        foreach ($sponsors as $sponsor) {
            Sponsor::create($sponsor);
        }
    }
} 